### ISSUE TITLE
Make a new release ...

### ISSUE THREAD

**Issue by hhugo** [ocaml/num#21]
that include #20

**Comment by dra27** [comment]
The main reason I've dragged my heels for a new `num` release is because last time it caused a lot of opam-repository pain with https://github.com/ocaml/opam-repository/issues/10925, and releasing a new version of the package triggers various CI systems to upgrade, it appears.

@RalfJung - if we do a new release, I'd really like to be able to have a repeatable environment to replicate the problem you've been seeing. If I've remembered correctly (and sorry if I've haven't) I've previously ground to a halt trying to replicate the problem because systems had been manually fixed. Would we be able to sync up with this release so that when a system breaks we can definitely either snapshot a VM or back-up the .opam root so that the problem can be reproduced?

**Comment by RalfJung** [comment]
I added reproducible instructions to https://github.com/ocaml/opam-repository/issues/10925. I do not think I have seen that bug on switches with ocaml >4.05, and our CI is using 4.07 these days. Also IIRC the problem arose when updating `ocamlfind`, not when updating `num` (but I might misremember, it's been a while).

But if the problem occurs on our CI, I can attempt to download the CI cache and extract the problematic switch.

**Comment by hhugo** [comment]
(just keeping this issue visible)

**Comment by xavierleroy** [comment]
Maybe it will be painful, but one release per year is reasonable.  Plus, YOLO.  https://github.com/ocaml/opam-repository/pull/17603 .

**Comment by hhugo** [comment]
thanks
