### ISSUE TITLE
nums.cmxs is installed without execute bit set

### ISSUE THREAD

**Issue by maroneze** [ocaml/num#32]
When installing `num` via opam, the installed file `lib/ocaml/nums.cmxs` has no execute bit set. This leads to errors under Cygwin, which seems to check for execution permission when loading a `.cmxs` file (I don't know exactly why, but it does).

Note that almost every .cmxs file has its bit set, e.g. `str.cmxs` and `unix.cmxs` do, so this behavior is at least inconsistent with most of the remaining OCaml platform.

It seems the current master version, based on dune, does not have this issue (I didn't try, but by default `dune` sets the bit), but since the latest release available on opam is 1.4, its old makefile is still used.

Maybe I could submit a patch to opam-repository which only applies to `{os = "windows"}`? Would it be acceptable?

**Comment by xavierleroy** [comment]
I agree the "x" bit on .cmxs files should be preserved during installation, or even always set.  The installation method for the Num library has changed several times since this library was separated from the core OCaml distribution, so I have no idea which of the installation methods is wrong and needs fixing.

**Comment by dra27** [comment]
It turned out all of the installation methods were wrong 🙂 The master branch should now work perfectly, so `opam pin add num --dev-repo` should workaround the problem until num.1.5 is released.
